version: '3'
services:
    prisma:
        image: prismagraphql/prisma:1.34
        restart: always
        ports:
            - '4466:4466'
        environment:
            PRISMA_CONFIG: |
                port: 4466
                # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
                # managementApiSecret: my-secret
                databases:
                  default:
                    connector: mysql
                    host: mysql
                    user: root
                    password: prisma
                    rawAccess: true
                    port: 3306
                    migrations: true
    mysql:
        image: mysql:5.7
        restart: always
        # Uncomment the next two lines to connect to your your database from outside the Docker environment, e.g. using a database GUI like Workbench
        ports:
            - '3307:3306'
        environment:
            MYSQL_ROOT_PASSWORD: prisma
        # volumes:
        #   - mysql:/var/lib/mysql
    bookstore_backend:
        image: 23079999/bookstorebackend:1.0.0
        build:
            context: ./bookstore-backend
            dockerfile: Dockerfile.dev
        ports:
            - 30306:30306
        env_file: ./bookstore-backend/config/dev.env
    bookstore_client:
        image: 23079999/bookstore-client:1.0.0
        build:
            context: ./bookstore-client-front
            dockerfile: Dockerfile
    bookstore_backend_admin:
        image: 23079999/bookstorebackendadmin:1.0.0
        build:
            context: ./bookstore-backend-admin
            dockerfile: Dockerfile.dev
    bookstore_admin_front:
        image: 23079999/bookstore-admin-front:1.0.0
        build:
            context: ./bookstore-admin-front
            dockerfile: Dockerfile
    image_server:
        image: 23079999/bookstore-img-server:1.0.0
        build:
            context: ./bookstore-image-server
            dockerfile: Dockerfile
volumes:
    mysql:
